# Generated by Django 3.2.8 on 2021-11-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='active_time',
            new_name='muscle_groups',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='muscle_group',
            new_name='reccomended_reps',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='reps',
            new_name='total_time',
        ),
    ]
