# Generated by Django 3.2.8 on 2021-11-22 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20211122_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='reccomended_reps',
            new_name='recommended_reps',
        ),
    ]
