# Generated by Django 3.2.8 on 2021-11-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_profile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmessage',
            name='timestamp',
        ),
    ]
