# Generated by Django 3.2.8 on 2021-11-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0006_remove_statusmessage_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
