# Generated by Django 3.2.8 on 2021-11-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0008_statusmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='_mini_fb_profile_friends_+', to='mini_fb.Profile'),
        ),
    ]
