# Generated by Django 3.2.8 on 2021-10-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
